{% set name = "conda-sphinx-theme" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/conda_sphinx_theme-{{ version }}.tar.gz
  sha256: 3ba3993914b27c7ff899434f06e3a0214395750f2864c4b483ff46656baea00f


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
  run:
    - pydata-sphinx-theme >=0.13.1,<0.16.0
    - python >={{ python_min }}
    - sphinx-favicon

test:
  imports:
    - conda_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/conda-sphinx-theme
  summary: Conda theme for Sphinx
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/conda-incubator/conda-sphinx-theme

extra:
  recipe-maintainers:
    - kathatherine
    - travishathaway
