{% set name = "conda-sphinx-theme" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/conda_sphinx_theme-{{ version }}.tar.gz
  sha256: 18548d0c9912c45775d0a6e0ef7f0246c601cc71a576fbb5c7296566c7c03db5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
  run:
    - pydata-sphinx-theme >=0.15,<0.16.0
    - python >={{ python_min }}
    - sphinx-favicon

test:
  imports:
    - conda_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/conda-sphinx-theme
  summary: Conda theme for Sphinx
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/conda-incubator/conda-sphinx-theme

extra:
  recipe-maintainers:
    - kathatherine
    - travishathaway
